config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home', as: 'home'

  resources :users, only: %i[show] do
    resources :profiles, only: %i[new create]
  end


  get '/complete/:team_id', to: 'teams#complete', as: 'complete'
  resources :teams, only: %i[show new create] do
    get '/mates', to: 'team_memberships#mates', as: 'mates'
    get '/loading', to: 'team_memberships#loading', as: 'loading'
    delete '/destroy', to: 'team_memberships#delete', as: 'delete'

    resources :team_memberships, only: %i[create random_mates]
    get '/review', to: 'teams#review'
    resources :team_reviews, only: %i[new create]
    resources :user_reviews, only: %i[new create]
  end
end

app/views/shared/_card_friend.html.erb
<%= link_to user_path(friend.id) do %>
  <div class='card-friend'>
    <% borderFriend = '' %>
    <% if friend.status == "ingame" %> <%= image_tag friend.image, class:"friend-image friend-ingame" %>
    <% elsif friend.status == "online" %> <%= image_tag friend.image, class:"friend-image friend-online" %>
    <% else friend.status == "away" %> <%= image_tag friend.image, class:"friend-image friend-away" %>
    <% end %>
    <i class="fas fa-circle <%= friend.status %>"></i>
    <div class='card-friend-info'>
      <h3><%= friend.username %>
        </h3>

      <% if !@user.shared_team_count(friend).zero? %>
        <p><i class="fas fa-heart"></i> <%= @user.shared_team_count(friend) %> games together </p>
      <% else %>
        <p>No game together yet <i class="fas fa-surprise"></i></p>
      <% end %>

      <div class='friend-games'>
        <% friend.games.each do |game|%>
          <p><%= game.name.upcase %> - <%= friend.game_profile(game) %></p>
        <% end %>
      </div>
    </div>

  </div>
<% end %>

app/views/shared/_card_game.html.erb
<div class="card-game" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), image-url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
  Breakfast
</div>

app/views/shared/_card_team.html.erb
<% if team.status == 'pending' %>
  <div class="card-team">
    <%= image_tag "https://i.pinimg.com/originals/9d/48/24/9d4824e004d497a1ce85c61db5ae26a6.jpg", class:"bottom-line pending" %>
    <div class="card-team-infos">
      <div>
        <h2>Team <%= team.id %></h2>
        <p>Game: &nbsp;<span><%= team.game.name.capitalize %></span></p>
        <p>Spirit: &nbsp;<span><%= team.spirit.capitalize %></span></p>
        <p>Rank: &nbsp;<span><%= team.rank_scale.capitalize %></span></p>
        <p>Type: &nbsp;<span><%= team.gender_choice.capitalize %></span></p>
      </div>
      <p class="card-team-status pending">PENDING</p>
    </div>
  </div>

<% elsif team.status == 'complete' %>
  <div class="card-team">
    <%= image_tag "https://bnetcmsus-a.akamaihd.net/cms/blog_header/nr/NRKCTXZNWRQ81519177975121.jpg", class:"bottom-line" %>
    <div class="card-team-infos">
      <div>
        <h2>Team <%= team.id %></h2>
        <p>Game: &nbsp;<span><%= team.game.name.capitalize %></span></p>
        <p>Spirit: &nbsp;<span><%= team.spirit.capitalize %></span></p>
        <p>Rank: &nbsp;<span><%= team.rank_scale.capitalize %></span></p>
        <p>Type: &nbsp;<span><%= team.gender_choice.capitalize %></span></p>
      </div>
      <p class="card-team-status ready">TEAM READY</p>
    </div>
  </div>

<% elsif team.status == 'ingame' %>
  <div class="card-team">
    <%= image_tag "https://ksassets.timeincuk.net/wp/uploads/sites/54/2014/11/OVR_Brigitte_007-1024x576.png" %>
    <div class="card-team-infos">
      <div>
        <h2>Team <%= team.id %></h2>
        <p>Game: &nbsp;<span><%= team.game.name.capitalize %></span></p>
        <p>Spirit: &nbsp;<span><%= team.spirit.capitalize %></span></p>
        <p>Rank: &nbsp;<span><%= team.rank_scale.capitalize %></span></p>
        <p>Type: &nbsp;<span><%= team.gender_choice.capitalize %></span></p>
      </div>
      <p class="card-team-status ingame">IN GAME</p>
    </div>
  </div>

<% elsif team.status == 'over' && team.team_review_for(current_user).present? %>
  <div class="card-team">
   <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRF5Hso0rfNz1V41JRKlAxh_H4nn7VcL_2P8sHHmyjWRtBRdP_KLQ"%>
    <div class="card-team-infos">
      <div>
        <h2>Team <%= team.id %></h2>
        <p>Game: &nbsp;<span><%= team.game.name.capitalize %></span></p>
        <p>Spirit: &nbsp;<span><%= team.spirit.capitalize %></span></p>
        <p>Rank: &nbsp;<span><%= team.rank_scale.capitalize %></span></p>
        <p>Type: &nbsp;<span><%= team.gender_choice.capitalize %></span></p>
      </div>
      <h2 class="card-team-pricing">
        <% unless team.average_rating.nil? %>
          <p class="stars"><% team.average_rating.round.times do %>
            <i class="fas fa-star"></i>
          <% end %></p>
        <% end %>
      </h2>
    </div>
  </div>

<% elsif team.status == 'over' && team.team_review_for(current_user).blank? %>
  <div class="card-team">
    <%= image_tag "https://i.kym-cdn.com/photos/images/newsfeed/001/122/517/890.jpg", class:'rpending-img'%>
    <div class="card-team-infos">
      <div>
        <h2>Team <%= team.id %></h2>
        <p>Game: &nbsp;<span><%= team.game.name.capitalize %></span></p>
        <p>Spirit: &nbsp;<span><%= team.spirit.capitalize %></span></p>
        <p>Rank: &nbsp;<span><%= team.rank_scale.capitalize %></span></p>
        <p>Type: &nbsp;<span><%= team.gender_choice.capitalize %></span></p>
      </div>
      <%= link_to team_review_path(team.id) do %>
        <p class="card-team-status rpending"><i class="fas fa-pen"></i> REVIEW PENDING</p>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_circle_container.html.erb
<% degs = ["deg0", "deg45", "deg135", "deg180", "deg225", "deg315"] %>
 <ul id="team" class='circle-container'>
    <h1 class="typed load-text"></h1>
    <% 6.times do |index| %>

      <% if index < @mems.length %>
        <% mem = @mems[index] %>
        <li id="<%= mem.id %>" class="<%= degs[index] %> tool <%= "owner" if mem.id == current_user.id %> <%=  "mate" if mem.id != current_user.id %> "><img class="avatar-large friend-image-sm" alt="avatar-large" src="<%= mem.image %>"/><span class="tooltiptext"><%= mem.username %></span></li>
      <% else %>
        <li class="<%= degs[index] %> empty"><%= image_tag "logo_mercy.png", class:"friend-image-sm", alt:"avatar-large" %></li>
      <% end %>
    <% end %>
  </ul>

app/views/shared/_feature_card.html.erb
<div class="feature-card feature-card-<%= color %>">
  <span class="<%= icon %>"></span>
  <h3><%= title %></h3>
  <p><%= para %></p>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_flip_card_team_review.html.erb
<div class="flipcard flipcard-team">
  <div class="flipcard-banner">
  </div>

  <div class="flipcard-inner">
    <div class="front">
      <h2>Now, rate your game</h2>
      <div id="rater"></div>
      <div class="button1 leave-comment">Leave a comment</div>
    </div>

    <div class="back">
      <h2>It worths a few words</h2>
      <div class="comment-box">
        <%= simple_form_for [@team, @team_review] do |f| %>
          <%= f.hidden_field :rating, :value => 5 %>
          <%= f.input :comment, label: false, placeholder: "Share your experience with the community.", as: :text, class: "review-comment" %>
          <%= f.button :submit, "Submit", class: "my-button btn-user-rating hidden" %>
        <% end %>
      </div>
      <i id="team-flip" class="fas fa-undo-alt"></i>
    </div>
  </div>
</div>

app/views/shared/_flip_card_user_review.html.erb
<div id="<%= user.id %>" class="flipcard flipcard-user">
  <div class="flipcard-banner">
    <%= image_tag team.mainrole_img(user) || 'https://vignette.wikia.nocookie.net/overwatch/images/5/50/Wiki-background/revision/latest/scale-to-width-down/640?cb=20171105231456', class:"team-banner-review" %>
    <%= image_tag user.image, class:"friend-image" %>
  </div>

  <%= simple_form_for [@team, @user_review], html: {id: "new_user_review_#{user.id}" } do |f| %>
    <div class="flipcard-inner">
        <div class="front">
          <h2>Enjoyed playing with </br><%= user.username %>?</h2>
          <div class="ok-comments">
            <%= f.hidden_field :user_reviewed_id, :value => user.id, id: "user_reviewed_id_#{user.id}" %>
            <%= f.input :add_friend, as: :boolean, boolean_style: :inline, :input_html => {id: "add_friend_#{user.id}", class: 'add_friend'} %>
            <%= f.input :endorse, as: :boolean, boolean_style: :inline, :class=> "user-review_checkbox", :input_html => {id: "endorse_#{user.id}", class: 'endorse'} %>
            <%= f.input :nok, label: "Not really", as: :boolean, boolean_style: :inline, :class=> "user-review_checkbox hidden", :input_html => {id: "nok_#{user.id}", class: 'nok'} %>
          </div>
        </div>

      <div class="back">
        <h2>Let <%= user.username %> know what was wrong</h2>
        <div class="nok-comments">
          <%= f.input :nok_positiveness, label: "Not positive", as: :boolean, boolean_style: :inline, :input_html => {id: "nok_positiveness_#{user.id}", class: 'nok_positiveness'} %>
          <%= f.input :nok_positiveness, label: "Not communicative", as: :boolean, boolean_style: :inline, :class=> "user-review_checkbox nok", :input_html => {id: "nok_communication_#{user.id}", class: 'nok_communication'} %>
          <%= f.input :nok_helpfulness, label: "Not helpful", as: :boolean, boolean_style: :inline, :class=> "user-review_checkbox nok", :input_html => {id: "nok_helpfulness_#{user.id}", class: 'nok_helpfulness'} %>
          <%= f.input :nok_respect, label: "Not respectful", as: :boolean, boolean_style: :inline, :class=> "user-review_checkbox nok", :input_html => {id: "nok_respect_#{user.id}", class: 'nok_respect'} %>
        </div>
        <i class="fas fa-undo-alt"></i>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Enjoy your next game</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
                <%= simple_form_for(User.new, as: :user, url: session_path(:user), wrapper: :horizontal_form) do |f| %>
          <div class="form-inputs text-dark form-login">
            <%= f.input :email,
                        required: false,
                        autofocus: true,
                        input_html: { autocomplete: "email" }
                         %>
            <%= f.input :password,
                        required: false,
                        input_html: { autocomplete: "current-password" }  %>
            </div>

          <div class="form-actions">
            <%= f.button :submit, "Login", class:"button2" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- navbar -->

<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="d-flex align-items-center">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "logo_Mercyv1.png", :class=>"toto",width: "30",  height: "30" %>
      <h3>MERCY</h3>
    <% end %>
  </div>

  <!-- USER SIGNED IN -->
  <div class="d-flex align-items-center">
    <% if user_signed_in? %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto d-flex justify-center align-items-center">
          <div class="navbar-text">
            <li class="nav-item active mr-2">
              <%= link_to new_team_path, class: "nav-link" do %>
                <span><i class="fas fa-search"></i> Find a player</span>
              <% end %>
            </li>
            <li class="nav-item active mr-4">
              <%= link_to "Create a team", new_team_path, class: "nav-link" %>
            </li>
            <li class="nav-item d-block d-sm-none">
              <%= link_to "My Profile", user_path(current_user.id), class: "nav-link" %>
            </li>
            <li class="nav-item  d-block d-sm-none">
              <%= link_to "Sign out", destroy_user_session_path, class: "nav-link" %>
            </li>
          </div>
          <li class="dropdown d-none d-sm-block">
            <% if current_user.image %>
              <%= image_tag current_user.image, class: "avatar-navbar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag 'nologin_profile.png', class: "avatar-navbar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "My Profile", user_path(current_user.id), class: "dropdown-item", id: "user-profile" %>
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        </ul>
      </div>
  </div>

  <!-- USER NOT SIGNED IN -->
  <% else %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul id="user-op" class="navbar-nav mr-auto">
        <div class="jototo">
          <li class="nav-item active">
            <a class="nav-link" data-toggle="modal" data-target="#exampleModal">Log in</a>
          </li class="nav-item active">
          <li class="nav-item active">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
        </div>
        <li class="dropdown d-none d-sm-block">
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
             <%= link_to "Log in", new_user_session_path, class: "dropdown-item" %>
             <%= link_to "Sign up", new_user_registration_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    </div>
  <% end %>
</div>
</div>

app/views/shared/_separator.html.erb
<div class="separator">
  <hr>
  <div class="separator-content">
    <%= title %>
    <div class="separator-badge">
      <%= score %>
    </div>
  </div>
  <hr>
</div>

app/views/shared/_user_profil_box.html.erb
<div class="profile-box">
  <div class="user-image">
    <%= image_tag @user.image, class:"avatar-xlarge" %>
  </div>
  <div class="user-tagname">
    <h2><%= @user.username %><br></h2>
      <h6>Only Pokemon matter</h6>
  </div>
  <div class="about-me">
    <p>About me: <br>Age: <%= @user.age %> y.o.<br>Location: Montreal, Canada</p>
  </div>
  <div class="user-mercy-stats">
    <% if @user.user_reviews != [] %>
      <p class="user-endorsement">
        <i class="fas fa-thumbs-up"></i>
        <span class="stats-number"> <%= UserReview.where(user_id: @user.id, endorse: true).count %></span>
        </br>NUMBER OF </br>ENDORSEMENTS </br>
      </p>
      <p class="user-as-friends">
        <i class="fas fa-heart"></i>
         <span class="stats-number"> <%= UserReview.where(user_id: @user.id, add_friend: true).count %> </span>
        </br>ADDED </br>AS FRIEND </br>
      </p>
      <p class="user-endorsement">
        <i class="fas fa-smile-beam"></i>
         <span class="stats-number"> <%= (UserReview.where(user_id: @user.id, endorse: true).count * 100) / UserReview.where(user_id: @user.id).count %>% </span>
        </br>POSITIVE </br>REVIEWS </br>
      </p>
    <% end %>
  </div>
  <p class="more-info">
    <i class="fab fa-discord"></i>
    <i class="fab fa-twitch"></i>
    <i class="fab fa-steam-symbol"></i>
  </p>
</div>

app/views/shared/_user_review_card.html.erb
    <!--       <p class="aka">aka</p> -->

    <!--   <p><%= user.username %></p> -->
<div class="comments">
    <% user_review = UserReview.new %>
      <%= simple_form_for [@team, user_review] do |f| %>
        <%= f.hidden_field :user_reviewed_id, :value => user.id %>
        <div class="inline-button">
          <%= f.input :add_friend, as: :boolean, boolean_style: :inline %>
          <%= f.input :endorse, as: :boolean, boolean_style: :inline, :class=> "user-review_checkbox" %>
          <%= f.input :nok, label: "Not really", as: :boolean, boolean_style: :inline, :class=> "user-review_checkbox" %>
        </div>
        <div class="nok-button hidden">
          <div class="nok positive"><%= f.input :nok_positiveness, label: "Not positive", as: :boolean, boolean_style: :inline %></div>
          <div class="nok com"><%= f.input :nok_communication, label: "Not communicative", as: :boolean, boolean_style: :inline, :class=> "user-review_checkbox nok" %></div>
          <div class="nok help"><%= f.input :nok_helpfulness, label: "Not helpful", as: :boolean, boolean_style: :inline, :class=> "user-review_checkbox nok" %></div>
          <div class="nok respect"><%= f.input :nok_respect, label: "Not respectful", as: :boolean, boolean_style: :inline, :class=> "user-review_checkbox nok" %></div>
        </div>
      </div>
      <%= f.button :submit, "Next", class: "my-button btn-user-rating" %>
      <% end %>
  </div>
</div>
 --> -->