config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home', as: 'home'

  resources :users, only: %i[show] do
    resources :profiles, only: %i[new create]
  end


  get '/complete/:team_id', to: 'teams#complete', as: 'complete'
  resources :teams, only: %i[show new create] do
    get '/mates', to: 'team_memberships#mates', as: 'mates'
    get '/loading', to: 'team_memberships#loading', as: 'loading'
    delete '/destroy', to: 'team_memberships#delete', as: 'delete'

    resources :team_memberships, only: %i[create random_mates]
    get '/review', to: 'teams#review'
    resources :team_reviews, only: %i[new create]
    resources :user_reviews, only: %i[new create]
  end
end

app/models/team_membership.rb
class TeamMembership < ApplicationRecord
  belongs_to :user
  belongs_to :team

  validates :user, :team, presence: true
end

app/controllers/team_memberships_controller.rb
class TeamMembershipsController < ApplicationController
  before_action :set_team, only: %i[mates create loading]
  skip_before_action :verify_authenticity_token, only: %i[ create delete]

  def mates
    redirect_to team_path(@team) if @team.status == "complete"

    @user = current_user
    friends = @user.friends.uniq
    mems = @team.team_memberships.pluck(:user_id)
    @mems = User.where(id: mems)

    indexes = []
    friends.each do |friend|
      @mems.each do |mem|
        indexes << friend.id if friend.id == mem.id
      end
    end
    temp = @user.friends.where.not(id: indexes)
    @friends = @user.friends.where(id: temp).order(username: :asc).uniq
  end

  def create
    head :bad_request if @team.team_memberships.length == 6

    membership = TeamMembership.new(team_params)
    if membership.save
      user = User.find(team_params["user_id"])
      user.status = "ingame"
      user.save!
      head :created
    else
      head :bad_request
    end
  end

  def delete
    membership = TeamMembership.where(team_params)

    if TeamMembership.destroy(membership[0].id)
      user = User.find(team_params["user_id"])
      user.status = "online"
      user.save!
      head :ok
    else
      head :bad_request
    end
  end

  def not_full(mems)
    return true if mems.length != 6
  end

  def loading
    mems = @team.team_memberships.pluck(:user_id)

    # get friends of friends
    if not_full(mems)
      mates = current_user.friends.pluck(:id)

      friend_friends = []

      mates.each do |friend|
        user = User.find(friend)
        friend_friends << user.friends.where.not(id: mates).pluck(:id)
      end

      friend_friends = friend_friends.flatten.uniq
      make_team(friend_friends, mems)

      #  get most endorsed that aren't your friends or your friends friends

      mems = @team.team_memberships.pluck(:user_id)
      if not_full(mems)
        users = User.where(status: "online").pluck(:id)

        lvl1 =  users - mates
        lvl2 = lvl1 - friend_friends

        lvl3 = User.where(id: lvl2).joins(:user_reviews).where("user_reviews.endorse = ?", true).pluck(:id)

        lvl3 = lvl3.flatten.uniq

        make_team(lvl3, mems)

        # get randoms

        mems = @team.team_memberships.pluck(:user_id)
        if not_full(mems)
          last_resorts = lvl3 - mems
          make_team(last_resorts, mems)
        end

      end
    end

    mems = @team.team_memberships.pluck(:user_id)
    @mems = User.where(id: mems)
    @team.status = "complete"
    @team.save!
  end

  private

  def make_team(mates, mems)
    mates.first(6 - mems.length).each do |people|
      next if people == current_user.id

      TeamMembership.create(
        user_id: people,
        team_id: @team.id
      )
    end
  end

  def team_params
    params.require(:team_membership).permit(:user_id, :team_id)
  end

  def set_team
    @team = Team.find(params[:team_id])
  end
end

app/views/team_memberships/loading.html.erb
<div class="container-loading">
  <div class="rails-default-error-page">
    <div class="tenor-gif-embed lobby"></div>
  </div>
    <h1> LOOKING FOR YOUR TEAM MATES </h1>

  <div class="team-circle2">
  <%= render 'shared/circle_container', mems: @team.users %>
  </div>

</div>



<script>

  function redirect(){
    window.location.href = "/teams/<%= @team.id %>";
  }
  setTimeout(redirect, 22000)


</script>

app/views/team_memberships/mates.html.erb
<div class="rails-default-error-page">
  <div class="tenor-gif-embed lobby"></div>
</div>

<div class="container-mates">
    <div id="<%= current_user.id %>" class="team-circle">
      <%= render 'shared/circle_container', mems: @mems.reverse %>
      <%= link_to "Complete the team", team_loading_path, class: "button1" %>

    </div>
<!--
  <div class="lobby-name">
    <h1><%= @user.username %><br>Main character D.va</h1>
  </div> -->

  <div class="friend-bar">
    <ul class="friend-list">
      <h2>MY FRIENDS</h2>
      <% @friends.each do |friend| %>
        <li id="<%= friend.id %>" class="friend" >
          <div class="friend-avatar-available">
            <% if friend.status == "ingame" %>
              <div class="friend-bar-image">
                <%= image_tag friend.image, class:"friend-image-sm friend-ingame" %>
                <i class="fas fa-circle <%= friend.status %>"></i>
              </div>
            <% elsif friend.status == "online" %>
              <div class="friend-bar-image">
                <%= image_tag friend.image, class:"friend-image-sm  friend-online" %>
                <i class="fas fa-circle <%= friend.status %>"></i>
              </div>
            <% else friend.status == "away" %>
              <div class="friend-bar-image">
                <%= image_tag friend.image, class:"friend-image-sm  friend-away" %>
                <i class="fas fa-circle <%= friend.status %>"></i>
              </div>
            <% end %>
          </div>

          <div class="friend-info">
            <p id="friend-username" class="info-<%= friend.status %>"><%= friend.username %></p>
            <p id="main-character">as. <%= friend.profile(@team).capitalize %></p>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>